name: Swift

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and run Tests
      run: xcodebuild -enableCodeCoverage YES -scheme SwiftPlantUML-Package -sdk macosx -destination 'platform=macOS' build test
    - name: Upload code coverage results
      run: bash <(curl -s https://codecov.io/bash) -t f913eaee-1802-4688-8b85-bbb28316592f

  install-verification:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install with Make
      run: |
        make install
        swiftplantuml --help
        man swiftplantuml | col -b # this will remove formatting and control characters as here needed for text output
        make uninstall
    - name: Install with Homebrew
      run: |
        brew install MarcoEidinger/formulae/swiftplantuml
        swiftplantuml --help
        brew uninstall swiftplantuml
